title: How to train your model "Pentester"
description: This blog focuses on the process of studying and training an LLM AI Model locally, for the use of an autonomous agent, associated with a specific task.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker